defaults:
  - dataset: cltsqa

model_id: base
mode: eval
cuda:
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1
learning_rate: 5e-5
adam_epsilon: 1e-8
weight_decay: 0.01
num_train_epochs: 10
max_sequence_length: 4096
text_maxlength: 180
n_context: 100
answer_maxlength: 60
max_query_length: 36
logging_steps: 20
max_grad_norm: 1.0
use_checkpoint: true
model_path:
n_gpu: 4 
