defaults:
  - dataset: cltsqa

model_id: nq
mode: eval
cuda:
per_gpu_train_batch_size: 1
learning_rate: 2e-5
adam_epsilon: 1e-8
weight_decay: 0.0
num_train_epochs: 10
max_sequence_length: 3600 # 3600
doc_stride: 2048 #2048
max_query_length: 36
logging_steps: 20
max_grad_norm: 1.0
model_path: 'checkpoints/bigbird/cl-one/checkpoint-0/'
n_gpu: 4
